### PR TITLE
Bugfix slim3 compatibility

### PR DESCRIPTION
**Pull request by llaville**
The compatibilty with zend expressive should be check. 
At least I confirm that it works with Slim3 !

### CODE REVIEW

**Comment by snapshotpl** [comment]
Thx! `getBasePath` method is custom method in uri implementation in slim?

**Comment by llaville** [comment]
yes. see https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Uri.php#L576

**Comment by llaville** [comment]
It seems that this fix seems unnecessary. I'll confirm you tomorrow.

**Comment by llaville** [comment]
I confirm. This fix is not necessary. Issue came from a problem in our environment !

**Comment by snapshotpl** [comment]
@llaville are you sure? I installed slim and debugbar doesn't work

**Comment by llaville** [comment]
@snapshotpl Can you give me the context where slim and debugbar won't run (versions / platforms)

I've tested myself both on Windows with PHP 5.6 and built-in server (cli-server) , and Linux with PHP 5.6 built-in server and also with Apache 2 and Nginx

**Pull request closed without merging**
